"""Initial migration

Revision ID: 1efb9a8ee6fd
Revises: 
Create Date: 2025-01-01 12:46:46.771943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efb9a8ee6fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('title2', sa.String(length=200), nullable=False),
    sa.Column('description2', sa.Text(), nullable=False),
    sa.Column('title3', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('title4', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
